### ISSUE TITLE
Hack Inn如下说：

### ISSUE THREAD

**Issue by rtcatc** [victor-infosec/conference#1]
您的喜欢是我的荣幸，如果有需要我可以直接把data打包给你呢。还可以帮忙代找中国大陆、中国台湾、法国等地的资料；另外欢迎关注我的微博，还有加我们的tg群，我还有很多资料（懒得上线的、不能上线的）。

**Comment by victor-infosec** [comment]
感谢恢复，我这边主要搜集安全会议技术类的议题，所以所有的data用不了那么多。我这边也会关注一些安全会议的资料，如果发现你的网站珊瑚没有的，可以发你，大家资源共享。安全本身就是开放共享的。
最近几个月，特殊时期，都在h w，没哟及时回复，见谅，非常高兴可以共同学习，共同进步。
